import pycountry
from Models.Country import Country

# must only be initialized once


class CountryList:
    def __init__(self):
        self.countryList = [
            "Laos",
            "Peru",
            "Korea, South",
            "Finland",
            "Netherlands",
            "Mauritania",
            "Seychelles",
            "Jordan",
            "Eswatini",
            "South Sudan",
            "Guyana",
            "Cameroon",
            "Botswana",
            "Uganda",
            "Andorra",
            "Guinea-Bissau",
            "Paraguay",
            "Togo",
            "Mongolia",
            "Lithuania",
            "Malta",
            "Senegal",
            "Namibia",
            "Azerbaijan",
            "Cuba",
            "Turkey",
            "Iran",
            "France",
            "Haiti",
            "Niger",
            "Philippines",
            "New Zealand",
            "Belarus",
            "Italy",
            "Egypt",
            "Iceland",
            "Bulgaria",
            "Saudi Arabia",
            "Holy See",
            "Equatorial Guinea",
            "Brazil",
            "Chile",
            "Dominica",
            "Slovakia",
            "Cambodia",
            "Taiwan*",
            "Zambia",
            "Romania",
            "Serbia",
            "Sao Tome and Principe",
            "Congo (Brazzaville)",
            "El Salvador",
            "Mexico",
            "Norway",
            "Morocco",
            "Sri Lanka",
            "Suriname",
            "Uruguay",
            "Kenya",
            "Afghanistan",
            "Albania",
            "Maldives",
            "Greece",
            "Liechtenstein",
            "Canada",
            "Czechia",
            "Portugal",
            "Ireland",
            "Montenegro",
            "Saint Vincent and the Grenadines",
            "Costa Rica",
            "Armenia",
            "Barbados",
            "Monaco",
            "Singapore",
            "Indonesia",
            "Oman",
            "Sweden",
            "Kuwait",
            "Cabo Verde",
            "Pakistan",
            "Israel",
            "United Kingdom",
            "Qatar",
            "Somalia",
            "Belgium",
            "Ecuador",
            "Ghana",
            "Liberia",
            "Rwanda",
            "MS Zaandam",
            "Antigua and Barbuda",
            "Burundi",
            "Kyrgyzstan",
            "North Macedonia",
            "United Arab Emirates",
            "Latvia",
            "Bahamas",
            "Sierra Leone",
            "Zimbabwe",
            "Saint Kitts and Nevis",
            "Cote d'Ivoire",
            "Japan",
            "Colombia",
            "Bolivia",
            "Guatemala",
            "Estonia",
            "China",
            "Trinidad and Tobago",
            "Lebanon",
            "Western Sahara",
            "Germany",
            "Bosnia and Herzegovina",
            "Libya",
            "Malaysia",
            "Slovenia",
            "Saint Lucia",
            "Nicaragua",
            "Luxembourg",
            "Nigeria",
            "Tanzania",
            "Gambia",
            "Mozambique",
            "Dominican Republic",
            "Chad",
            "Australia",
            "Djibouti",
            "Eritrea",
            "Uzbekistan",
            "Thailand",
            "Burma",
            "Tunisia",
            "India",
            "West Bank and Gaza",
            "Angola",
            "Diamond Princess",
            "Panama",
            "San Marino",
            "Yemen",
            "Sudan",
            "Algeria",
            "Vietnam",
            "Austria",
            "Central African Republic",
            "Malawi",
            "Spain",
            "Madagascar",
            "Argentina",
            "Fiji",
            "Switzerland",
            "Syria",
            "Bahrain",
            "South Africa",
            "Mauritius",
            "Poland",
            "Congo (Kinshasa)",
            "Benin",
            "Ethiopia",
            "Gabon",
            "Timor-Leste",
            "Belize",
            "Guinea",
            "Bhutan",
            "US",
            "Croatia",
            "Bangladesh",
            "Burkina Faso",
            "Mali",
            "Moldova",
            "Russia",
            "Papua New Guinea",
            "Jamaica",
            "Denmark",
            "Brunei",
            "Georgia",
            "Honduras",
            "Iraq",
            "Kosovo",
            "Ukraine",
            "Cyprus",
            "Nepal",
            "Venezuela",
            "Grenada",
            "Kazakhstan",
            "Hungary",
        ]

